In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np
from pathlib import Path

Data pulled from: https://www.cancer-rates.info/tx/

Years 2015-2019 * Breast Cancer (Either Sex) * County Level

In [17]:
#Years 2015-2019 * Breast Cancer (Either Sex) * County Level * ALL Race/Ethnicity

csv_path = Path("CSV_Files/bcancertexas.csv")
breast_cancer_texas = pd.read_csv(csv_path, skiprows=2)
breast_cancer_texas.head()

,County,Population at Risk,Cases,Crude Rate,Age-adjusted Rate,95% Confidence Interval-Lower Limit,95% Confidence Interval-Upper Limit
0,Armstrong,9317.0,~,~,~,~,~
1,Cottle,6968.0,~,~,~,~,~
2,Irion,7759.0,~,~,~,~,~
3,Mills,24433.0,30,122.8,86.8,55.0,131.7
4,Blanco,57426.0,69,120.2,79.5,59.8,104.3

In [18]:
breast_cancer_texas.columns

Index(['County', 'Population at Risk', 'Cases', 'Crude Rate',
       'Age-adjusted Rate', '95% Confidence Interval-Lower Limit',
       '95% Confidence Interval-Upper Limit'],
      dtype='object')

In [19]:
#Years 2015-2019 * Breast Cancer (Either Sex) * County Level * Non Hispanic Whites

csv_path2 = Path("CSV_Files/incidenceNHW.csv")
breast_cancer_texas_NHW = pd.read_csv(csv_path2, skiprows=2)
breast_cancer_texas_NHW

,County,Population at Risk,Cases,Crude Rate,Age-adjusted Rate,95% Confidence Interval-Lower Limit,95% Confidence Interval-Upper Limit
0,Armstrong,8315.0,~,~,~,~,~
1,Maverick,8017.0,~,~,~,~,~
2,Irion,5527.0,~,~,~,~,~
3,Lipscomb,10697.0,~,~,~,~,~
4,Menard,6451.0,~,~,~,~,~
...,...,...,...,...,...,...,...
228,Sutton,6940.0,~,~,~,~,~
229,STATE,60593193.0,53711,88.6,68.3,67.7,68.9
230,"Note: All rates are per 100,000. Rates are age...",NaN,NaN,NaN,NaN,NaN,NaN
231,"Rates generated on Jun 12, 2023.",NaN,NaN,NaN,NaN,NaN,NaN
232,"Cancer Incidence File, Apr 2022.",NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
#Years 2015-2019 * Breast Cancer (Either Sex) * County Level * Non Hispanic Black

csv_path3 = Path("CSV_Files/incidenceNHBlack.csv")
breast_cancer_texas_NHB = pd.read_csv(csv_path3, skiprows=2)
breast_cancer_texas_NHB

,County,Population at Risk,Cases,Crude Rate,Age-adjusted Rate,95% Confidence Interval-Lower Limit,95% Confidence Interval-Upper Limit
0,Cooke,7096.0,~,~,~,~,~
1,Wood,12125.0,~,~,~,~,~
2,Lamar,34229.0,34,99.3,101.3,69.2,143.1
3,Hill,12095.0,~,~,~,~,~
4,Bastrop,30557.0,34,111.3,97.9,67.1,138.5
...,...,...,...,...,...,...,...
112,Karnes,6539.0,0,0.0,0.0,0.0,0.0
113,STATE,17407751.0,10894,62.6,69.6,68.3,71.0
114,"Note: All rates are per 100,000. Rates are age...",NaN,NaN,NaN,NaN,NaN,NaN
115,"Rates generated on Jun 12, 2023.",NaN,NaN,NaN,NaN,NaN,NaN
116,"Cancer Incidence File, Apr 2022.",NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Years 2015-2019 * Breast Cancer (Either Sex) * County Level * Hispanic

csv_path4 = Path("CSV_Files/incidenceHisp.csv")
breast_cancer_texas_hisp = pd.read_csv(csv_path4, skiprows=2)
breast_cancer_texas_hisp

,County,Population at Risk,Cases,Crude Rate,Age-adjusted Rate,95% Confidence Interval-Lower Limit,95% Confidence Interval-Upper Limit
0,Blanco,11178.0,~,~,~,~,~
1,Lavaca,18865.0,~,~,~,~,~
2,Cass,6811.0,~,~,~,~,~
3,Eastland,14924.0,~,~,~,~,~
4,Wheeler,6955.0,~,~,~,~,~
...,...,...,...,...,...,...,...
212,Lipscomb,5695.0,0,0.0,0.0,0.0,0.0
213,STATE,55427467.0,20437,36.9,49.7,49.0,50.4
214,"Note: All rates are per 100,000. Rates are age...",NaN,NaN,NaN,NaN,NaN,NaN
215,"Rates generated on Jun 12, 2023.",NaN,NaN,NaN,NaN,NaN,NaN
216,"Cancer Incidence File, Apr 2022.",NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#Years 2015-2019 * Breast Cancer (Either Sex) * County Level * API

csv_path5 = Path("CSV_Files/incidenceAPI.csv")
breast_cancer_texas_API = pd.read_csv(csv_path5, skiprows=2)
breast_cancer_texas_API

,County,Population at Risk,Cases,Crude Rate,Age-adjusted Rate,95% Confidence Interval-Lower Limit,95% Confidence Interval-Upper Limit
0,Victoria,6384.0,~,~,~,~,~
1,McLennan,22986.0,~,~,~,~,~
2,Tom Green,8807.0,~,~,~,~,~
3,Wichita,15741.0,~,~,~,~,~
4,Taylor,16556.0,~,~,~,~,~
5,Galveston,60194.0,44,73.1,68.4,49.2,93.0
6,Midland,18365.0,~,~,~,~,~
7,Coryell,12201.0,~,~,~,~,~
8,Ellis,8302.0,~,~,~,~,~
9,Bell,71818.0,37,51.5,51.9,36.1,72.3
10,Collin,775901.0,342,44.1,51.4,45.7,57.6
11,Harris,1728755.0,856,49.5,47.6,44.4,51.0
12,Tarrant,614113.0,290,47.2,47.6,42.1,53.5
13,Johnson,11733.0,~,~,~,~,~
14,Fort Bend,798538.0,371,46.5,45.9,41.2,51.0
15,Denton,394064.0,164,41.6,45.9,38.7,54.0
16,Montgomery,93623.0,42,44.9,45.4,32.3,62.3
17,Travis,449885.0,160,35.6,45.3,38.0,53.5
18,Gregg,9418.0,~,~,~,~,~
19,Randall,12395.0,~,~,~,~,~
20,Smith,19698.0,~,~,~,~,~
21,Dallas,871355.0,333,38.2,41.6,37.1,46.5
22,Williamson,208832.0,74,35.4,40.5,31.5,51.5
23,Brazos,72533.0,~,~,~,~,~
24,Calhoun,5875.0,~,~,~,~,~
25,Bexar,318173.0,119,37.4,39.2,32.3,47.0
26,Hays,19044.0,~,~,~,~,~
27,Orange,5442.0,~,~,~,~,~
28,Guadalupe,17565.0,~,~,~,~,~
29,Kaufman,8628.0,~,~,~,~,~
30,El Paso,58686.0,21,35.8,35.6,22.0,54.6
31,Nueces,40200.0,~,~,~,~,~
32,Potter,33067.0,~,~,~,~,~
33,Comal,9978.0,~,~,~,~,~
34,Webb,7291.0,~,~,~,~,~
35,Brazoria,125496.0,43,34.3,32.4,23.4,43.9
36,Cameron,15043.0,~,~,~,~,~
37,Jefferson,50835.0,17,33.4,28.4,16.5,46.5
38,Rockwall,16274.0,~,~,~,~,~
39,Hidalgo,41693.0,~,~,~,~,~
40,Ector,10357.0,~,~,~,~,~
41,Lubbock,38427.0,~,~,~,~,~
42,Hunt,7888.0,~,~,~,~,~
43,Bowie,6495.0,~,~,~,~,~
44,Grayson,10513.0,~,~,~,~,~
45,Moore,7251.0,0,0.0,0.0,0.0,0.0
46,STATE,7332551.0,3156,43.0,45.2,43.6,46.8
47,"Note: All rates are per 100,000. Rates are age...",NaN,NaN,NaN,NaN,NaN,NaN
48,"Rates generated on Jun 12, 2023.",NaN,NaN,NaN,NaN,NaN,NaN
49,"Cancer Incidence File, Apr 2022.",NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#Years 2015-2019 * Breast Cancer (Either Sex) * County Level * Native American & Alaskans

csv_path6 = Path("CSV_Files/incidenceNA.csv")
breast_cancer_texas_NA = pd.read_csv(csv_path6, skiprows=2)
breast_cancer_texas_NA

,County,Population at Risk,Cases,Crude Rate,Age-adjusted Rate,95% Confidence Interval-Lower Limit,95% Confidence Interval-Upper Limit
0,Fort Bend,9663.0,24,248.4,297.3,186.1,448.7
1,Collin,22337.0,33,147.7,152.1,103.4,216.1
2,Williamson,10043.0,~,~,~,~,~
3,Travis,18002.0,21,116.7,109.0,65.3,173.5
4,Grayson,9924.0,~,~,~,~,~
5,Dallas,45190.0,43,95.2,87.2,62.4,118.8
6,Denton,21230.0,18,84.8,85.6,48.6,140.4
7,Lubbock,6439.0,~,~,~,~,~
8,Tarrant,45403.0,38,83.7,75.2,52.2,105.2
9,Harris,55454.0,35,63.1,56.2,38.3,79.9
10,Brazoria,7121.0,~,~,~,~,~
11,Parker,5264.0,~,~,~,~,~
12,Montgomery,11914.0,~,~,~,~,~
13,Bexar,27904.0,~,~,~,~,~
14,Bell,9245.0,~,~,~,~,~
15,Wichita,5625.0,~,~,~,~,~
16,El Paso,12891.0,0,0.0,0.0,0.0,0.0
17,Galveston,6791.0,0,0.0,0.0,0.0,0.0
18,STATE,524015.0,378,72.1,65.2,58.6,72.5
19,"Note: All rates are per 100,000. Rates are age...",NaN,NaN,NaN,NaN,NaN,NaN
20,"Rates generated on Jun 12, 2023.",NaN,NaN,NaN,NaN,NaN,NaN
21,"Cancer Incidence File, Apr 2022.",NaN,NaN,NaN,NaN,NaN,NaN